### ISSUE TITLE
How to test React App in Saucelabs?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-saucelabs#6]
What is the easiest way to test a React app using Saucelabs?
@nikhilaravi want to investigate this for us?

**Comment by naazy** [comment]
could REALLY do with help with this ;)

**Comment by naazy** [comment]
@nelsonic @nikhilaravi - I think i've figured this out and am happy to help write this up! there's very little useful online documentation for using tape shallow rendering tests with saucelabs...

**Comment by nelsonic** [comment]
@naazy if you can write up some explanation it would be _amaze_! :+1:

**Comment by naazy** [comment]
@nelsonic - will do. The npm module zuul makes this a lot easier! https://github.com/defunctzombie/zuul

**Comment by naazy** [comment]
@nelsonic - i have written this up and committed but am unable to push and make a pull request because i don't have the right permissions!

**Comment by iteles** [comment]
@naazy You do now!

**Comment by naazy** [comment]
@iteles you're going to regret that!

**Comment by naazy** [comment]
Done - but my mark down is a bit messed up so I'll fix later today.
